<?php

namespace App\Models;

use App\Enums\InvoiceStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends Model
{
    use SoftDeletes;

    public function patient(): BelongsTo
    {
        return $this->belongsTo(Patient::class);
    }

    protected function casts(): array
    {
        return [
            'date' => 'date',
            'status' => InvoiceStatus::class
        ];
    }

    protected static function booting()
    {
        static::creating(function(Invoice $invoice){
            if(!$invoice->status){
                $invoice->status = InvoiceStatus::OPEN->value;
            }
        });
        parent::booting(); // TODO: Change the autogenerated stub
    }
}
